# Generated by Django 4.2.1 on 2023-05-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='teachers', through='myapps.Lesson', to='myapps.student'),
        ),
    ]
