# Generated by Django 4.2.1 on 2023-05-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_teacher_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
